---
name: HTML-Template-Compiled-Plugin-I18N
version: 1.03
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'HTML::Template::Compiled::Plugin::I18N - Internationalization for HTC'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Class::Singleton: 0
  Cwd: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  parent: 0
requires:
  Carp: 0
  Data::Dumper: 0
  English: 0
  HTML::Template::Compiled: 0.93
  Hash::Util: 0
  perl: 5.006
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.340201
provides:
  HTML::Template::Compiled::Plugin::I18N:
    file: lib/HTML/Template/Compiled/Plugin/I18N.pm
    version: 1.03
  HTML::Template::Compiled::Plugin::I18N::DefaultTranslator:
    file: lib/HTML/Template/Compiled/Plugin/I18N/DefaultTranslator.pm
    version: 1.02
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
